### ISSUE TITLE
Per figure notes italicized

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#194]
Allow in-dance notes to be visually distingushable (italic)

**Comment by dcmorse** [comment]
per-figure notes or per-dance notes?

**Comment by dcmorse** [comment]
per-dance notes can be italicized by clapping the text in a matching pair of underscores.

**Comment by cranhandler** [comment]
Per figure notes.

**Comment by dcmorse** [comment]
This seems like a reasonable request, but it's harder than typing `<i> </i>` because of security structure. It's hard to inject html into the figure printing. So if it pays to rip off that bandage, I wanna get *all* the formatting issues with that string dealt with. Do you have other html in the fiugre strings you'd like dealt with?

For example:
I'd like beats to be handled another way. Printing "for 6" on the end of everything seems a little cludgy, and in the dance editor and maybe dance viewer, I'd consider having a separate column that displayed beats for each figure.

**Comment by dcmorse** [comment]
This is structurally hard for the value it provides. Closing this for now. :(
