### ISSUE TITLE
Add Figure placement

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#195]
I generally attempt to add figures when I'm at the end of the dance.

Alternately this could auto-add a new figure until I have reached 64 beats. But even if I want a 0 beat figure at the end, I'd want the 'add a figure' button to appear for me once I've hit the end.

Maybe just a last 'tab' after the last figure takes me to 'add a figure' for the short term?

**Comment by dcmorse** [comment]
You're saying you want the "Add Figure" button after the figures, not before, because that puts it next to the thing it acts on. That makes sense. 

The reason it's currently before, not at the end, is because clicking it changes the number of figures, and if the button were at the end, that'd cause the button to get squeezed down out from under the mouse cursor. Thus for the use case of adding 2+ figures at the same time, the UI dodges the user's mouse. By putting the Add Figure button above the figures, it's stable regardless of the number of figures. 

The same mechanic applies to the Delete Figure button. 

You've argued persuasively in the past that these buttons should affect the selected figure, not the end of the dance. That might mitigate this confusion, though it has it's own issues, and probably deserves it's own thread.

I don't see a clear advantage of doing it either way, and want to make sure all the trade-offs are understood before taking action.

**Comment by cranhandler** [comment]
I do everything from a keyboard and mouse ui is irrelevant.

**Comment by dcmorse** [comment]
I hear you. The focus is on making things work for users on their phones. Mouse second. Keyboard third. Closing for now.
