### ISSUE TITLE
Browser 'back' button can't return to a complex dance filter

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#221]
I execute a complex search (has petronella and no box circulate and no contra corners)
I look at a dance (Penicillin), but I see it has gyres and my program is too gyre-heavy

I press 'back' to resume my search and add 'no gyre'

but of course it's all blanked :( 

I don't know if it's easy to force the browser to remember the most-recent state, or if I want a checkbox for 'temporarily save search template.' I really hope the former.

**Comment by dcmorse** [comment]
Yrah. It sucks. My work around is to open links in new tabs until I learn
more about what's going on. I haven't even done a web search on it yet.

On Oct 28, 2017 8:33 AM, "cranhandler" <notifications@github.com> wrote:

I execute a complex search (has petronella and no box circulate and no
contra corners)
I look at a dance (Penicillin), but I see it has gyres and my program is
too gyre-heavy

I press 'back' to resume my search and add 'no gyre'

but of course it's all blanked :(

I don't know if it's easy to force the browser to remember the most-recent
state, or if I want a checkbox for 'temporarily save search template.' I
really hope the former.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dcmorse/contra/issues/221>, or mute the thread

**Comment by dcmorse** [comment]
See https://stackoverflow.com/a/17010046/5158597
When we navigate away, all that DOM gets flushed.
